name: MacSamurai
favicon: null
layout_spectrum: 0.7404920153785497
typography_spectrum: 0.168611831497401
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.23415093799121678
  lightness: 0.5990380991715938
  saturation: 0.35330782691016793
  rhythmicContrast: 0.9680522847920656
purpose: []
